### ISSUE TITLE
request to join the IG-workflows

### ISSUE THREAD

**Issue by AdamBelloum** [CLARIAH/IG-Workflows#2]
hi 

My name is Adam Belloum I work as a techLead for the eScience Center and I'm interested to join the  IG-workflows. 

Best
Adam

**Comment by proycon** [comment]
Very good! Welcome! We didn't really get underway yet, hopefully we can make a real start soon.

**Comment by proycon** [comment]
@AdamBelloum  Please make sure you 'watch' this repository (click the watch button on github) so you'll be automatically notified of any discussions.
