### ISSUE TITLE
Bash to CWL

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/IG-Workflows#5]
Just wondering if the upcoming [nl-rse meetup](https://nl-rse.org/events/2020-12-16-meetup.html) might be of interest to this interest group?

**Comment by proycon** [comment]
Thanks for sharing! That looks relevant indeed. Though it seems the topic is reversed "bash to CWL" rather than "CWL to bash", which I would actually find more interesting.

**Comment by c-martinez** [comment]
Yes, I got it wrong on the title of the issue, sorry -- changed it now. Hope it will still be useful and to see some of you there :-)
